MAIN_PROMPT = """\
"Extract data from this medical form. Here's the OCR text to help you:\n\n"
                            "Return a JSON object with EXACTLY this structure (populated with REAL values from the form,\n\n "
                            "not placeholders or fabricated data):\n\n"
                            '{\n'
                            '  "provider": {\n'
                            '    "providerName": "",\n'
                            '    "insuranceCompanyName": "",\n'
                            '    "tpaCompanyName": "",\n'
                            '    "patientFileNumber": "",\n'
                            '    "dept": "",\n'
                            '    "single": null,\n'
                            '    "married": null,\n'
                            '    "planType": "",\n'
                            '    "dateOfVisit": "",\n'
                            '    "newVisit": null,\n'
                            '    "followUp": null,\n'
                            '    "refill": null,\n'
                            '    "walkIn": null,\n'
                            '    "referral": null,\n'
                            '    "approvalDateTime": "",\n'
                            '    "approvalValidity": ""\n'
                            '  },\n'
                            '  "insured": {\n'
                            '    "insuredName": "",\n'
                            '    "idCardNo": "",\n'
                            '    "nationalId": "",\n'
                            '    "policyNo": "",\n'
                            '    "memberSince": "",\n'
                            '    "memberType": "",\n'
                            '    "expiryDate": "",\n'
                            '    "policyHolder": "",\n'
                            '    "entryDate": "",\n'
                            '    "class": "",\n'
                            '    "approval": "",\n'
                            '    "approvalReferrenceNumber": "",\n'
                            '    "approvalStatus": "",\n'
                            '    "approvalType": "",\n'
                            '    "message": "",\n'
                            '    "adjudicationPayer": "",\n'
                            '    "payer": ""\n'
                            '  },\n'
                            '  "patient": {\n'
                            '    "sex": "",\n'
                            '    "age": "",\n'
                            '    "gender": ""\n'
                            '  },\n'
                            '  "visitDetails": {\n'
                            '    "inpatient": null,\n'
                            '    "outpatient": null,\n'
                            '    "emergencyCase": null,\n'
                            '    "emergencyCareLevel": "",\n'
                            '    "physicianName": "",\n'
                            '    "bp": "",\n'
                            '    "pulse": "",\n'
                            '    "temperature": "",\n'
                            '    "weight": "",\n'
                            '    "height": "",\n'
                            '    "rr": "",\n'
                            '    "durationOfIllness": "",\n'
                            '    "chiefComplaints": "",\n'
                            '    "significantSigns": "",\n'
                            '    "possibleLineOfTreatment": "",\n'
                            '    "otherConditions": ""\n'
                            '  },\n'
                            '  "diagnosis": {\n'
                            '    "diagnosis": "",\n'
                            '    "principalCode": ""\n'
                            '    "secondCode": "",\n'
                            '    "thirdCode": "",\n'
                            '    "fourthCode": "",\n'
                            '    "fifthCode": "",\n'
                            '    "sixthCode": ""\n'
                            '  },\n'
                            '  "management": {\n'
                            '    "chronic": null,\n'
                            '    "congenital": null,\n'
                            '    "rta": null,\n'
                            '    "workRelated": null,\n'
                            '    "vaccination": null,\n'
                            '    "checkUp": null,\n'
                            '    "psychiatric": null,\n'
                            '    "infertility": null,\n'
                            '    "pregnancy": null,\n'
                            '    "lmp": ""\n'
                            '  },\n'
                            '  "suggestiveLinesOfManagement": "",\n'
                            '  "services": [\n'
                            '    {\n'
                            '      "codeService": null,\n'
                            '      "type": "",\n'
                            '      "reqQty": null,\n'
                            '      "reqCost": null,\n'
                            '      "grossAmount": null,\n'
                            '      "appQty": null,\n'
                            '      "appCost": null,\n'
                            '      "appGross": null,\n'
                            '      "note": ""\n'
                            '      }\n'
                            '    ],\n'
                            '  "completedBy": {\n'
                            '    "providerApproval": "",\n'
                            '    "completedCodedBy": "",\n'
                            '    "signature": "",\n'
                            '    "date": ""\n'
                            '  },\n'
                            '  "medications": [\n'
                            '    {\n'
                            '      "medicationName": "",\n'
                            '      "type": "",\n'
                            '      "reqQty": null,\n'
                            '      "reqCost": null,\n'
                            '      "grossAmount": null,\n'
                            '      "appQty": null,\n'
                            '      "appCost": null,\n'
                            '      "appGross": null,\n'
                            '      "note": ""\n'
                            '      }\n'
                            '    ],\n'
                            '  "caseManagementForm": {\n'
                            '    "caseManagementFormIncluded": null,\n'
                            '    "possibleLineOfManagement": "",\n'
                            '    "estimatedLengthOfStay": "",\n'
                            '    "expectedDateOfAdmission": "",\n'
                            '    "estimatedCost": null,\n'
                            '    "estimatedGross": null,\n'
                            '    "totalApprovedCost": null,\n'
                            '    "approvedLengthOfStay": "",\n'
                            '    "providerComments": ""\n'
                            '  },\n'                            
                            '  "certification": {\n'
                            '    "physicianCertification": "",\n'
                            '    "physicianSignature": null,\n'
                            '    "physicianSignatureDate": "",\n'
                            '    "patientCertification": "",\n'
                            '    "patientName": "",\n'
                            '    "patientRelationship": "",\n'
                            '    "patientSignature": null,\n'
                            '    "patientSignatureDate": ""\n'
                            '  },\n'
                            '  "insuranceApproval": {\n'
                            '    "approved": null,\n'
                            '    "notApproved": null,\n'
                            '    "approvalNo": "",\n'
                            '    "approvalValidity": "",\n'
                            '    "comments": "",\n'
                            '    "approvedDisapprovedBy": "",\n'
                            '    "signature": "",\n'
                            '    "date": ""\n'
                            '  }\n'
                            '}\n\n'
                            "CRITICAL INSTRUCTIONS:\n"
                            "1. Use Boolean values (true/false) ONLY for checkbox fields that are clearly marked.\n"   
                            "2. Use null for missing or unreadable numeric values\n"
                            "3. Use empty strings for missing or unreadable text values\n"
                            "4. Populate ONLY fields that you can CLEARLY identify in the form\n"
                            "5. NEVER guess or make up data - empty values are better than incorrect data\n"
                            "6. Pay EXTRA ATTENTION to numbers and digits - don't confuse similar digits (e.g., 0/8, 1/7, 5/9)\n"
                            "7. If you're unsure about a digit, use an empty string rather than guessing\n"
                            "8. DO NOT use placeholder text like 'N/A', 'Unknown', etc. - use empty string or null instead\n"
                            "9. For dates, follow the exact format as shown in the form\n"
                            "10. Extract ONLY information present in the form image or OCR text\n"
                            "11. **Parenthesis are Checkboxes, if they contain any symbols or letters they should be considered checked (true) otherwise they are not checked (false)**\n"
                            "12. CRITICAL: If you cannot read something with 100% certainty, you MUST leave it empty - NEVER guess. "
                            "13. Leaving fields empty is BETTER than fabricating data. "
                            "14. Pay extremely close attention to numbers and digits - never substitute similar-looking "
                            "15. digits (e.g., don't mistake 0 for 8, or 9 for 5). "
                            "16. A name may continue in the next line, you MUST extract it all\n"
                            "17. Some values may be written in Arabic language, don't translate them, just extract the data as it is.\n"
"""